repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: 'v2.3.0'
  hooks:
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer
    - id: flake8
      args:
        - --max-line=120
    - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v4.3.21'
  hooks:
    - id: isort
- repo: https://github.com/ambv/black
  rev: '19.10b0'
  hooks:
    - id: black
