version: '3'

services:
  app:
    build: .
    image: ubilux
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - ".env"
      - ".env-local"
  redis:
    image: redis:5.0-alpine
    ports:
      - 6379:6379
    command: ["redis-server", "--notify-keyspace-events", "K$$"]
