version: "3.7"

services:
  app:
    build: .
    # image: "umat/ubilux:latest"
    expose:
      - 8000
    env_file:
      - ".env"
    depends_on:
      - redis
    restart: on-failure
  redis:
    image: "redis:5.0-alpine"
    ports:
      - 6739:6739
    command: ["redis-server", "--notify-keyspace-events", "K$$"]
  nginx:
    build: ./nginx
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
